<?php
//services default pages
$t->clearChilds();
$doc->Title = "WEB SERVICES - [".igk_web_get_config("website_title")."]";
$services = $params["services"];
$doc->setHeaderColor("#af104f");
igk_google_addfont($doc,"Roboto", 400);


$t->setClass("google-Roboto");
//header
$dv = $t->addDiv()->setClass("header");
$dv->addHeaderBar("Services");

$bar = $t->addActionBar();

$t->addDiv()->addQuote()->Content= R::gets("List of services");
//$body
$dv = $t->addDiv()->setClass("content");
$row = $dv->addContainer()->addRow();
if (igk_count($services) <=0){
	$row->addCol()->addColViewBox()->Content = R::ngets("No services found");
}
else{
	$row->addCol("igk-col-3-3")->addArticle($ctrl, $ctrl->getParentArticle("services.list.template"), $ctrl->getServices());
}
$t->addDiv()->setClass("footer")->addContainer()->addSingleRowCol()->addDiv()->addIGKCopyRight();