<?php

igk_google_addfont($doc, "Roboto");
$doc->setHeaderColor("#0064FF");//"#FFA500");
// $doc->Title = R::ngets("title.app_1", $ctrl->ServiceName);

$t->clearChilds();
$t->Content = null;
$t["class"] = "google-Roboto";

$n = $t->addDiv();

$r = $n->addDiv()->setStyle("padding-left:0px; padding-right:0px; margin-left:0px; margin-right:0px;overflow:hidden; background-color:#0064ff; color:#fefefe");
$h1 = $r->addDiv()
->setStyle("margin-left:-10px; margin-right:-10px; position:relative;")
->setClass("igk-col-lg-12-2 fith presentation")->addContainer()->addSingleRowCol();

// $dv = $h1->addDiv();
// $dv["class"]="posab fith bdr-1";
// $dv["style"]="z-index:1";
// $dv->addA($ctrl->getRootUri())->Content = "back";

$ct = $h1->addDiv()
->setClass("dispb no-decoration");
$ct->add("span")
->setClass("dispib posr")
->setStyle("left:10px; top:12px;")
->Content = igk_web_get_config("company_name");
$ct->addDiv()->setClass("igk-title-4")->Content = $ctrl->ServiceName;
$r->addDiv()->setClass("igk-col-lg-12-10 .ibox");

// return;


 // $r = $h->addRow()->setClass("no-margin");
	// $h1 = $r->addDiv()
	// ->setClass(" igk-col-lg-12-2 fith presentation");
	// $t = $h1->addDiv()
	// ->setClass("dispb no-decoration");

	// $r->add("span")
	// ->setClass("dispib posr")
	// ->setStyle("left:10px; top:12px;")
	// ->Content = igk_web_get_config("company_name");//igk_sys_domain_name();


	// $r->addDiv()->setClass("igk-title-4")->Content = $ctrl->ServiceName;
// $r->addDiv()->setClass("igk-col-lg-12-10 .ibox");




 $t->addDiv()
 ->addContainer()->addSingleRowCol()->addDiv()->Content = $ctrl->getServiceDescription();//addSectionTitle(4)->addDiv()->Content = "Service used to list all world country";

$n = $t->addWebMasterNode()->addRow()->setClass("no-margin")->addCol()->addDiv();
$ul = $n->add("ul");
$ul->addLi()->Content = "Location : ".$ctrl->getDeclaredFileName();

 $t->addDiv()->addContainer()->addRow()->addCol("igk-col-3-3")->addDiv()->addNotifyHost();

 $t->addDiv()->addContainer()->addRow()->addCol("igk-col-3-3")->addDiv()
 ->addArticle($ctrl,
 $ctrl->getParentArticle("list.functions.template"),
 $ctrl->getExposedServiceFunction()
 );

 //start web master setting node
 $ctn = $t->addWebMasterNode()->addDiv()->addContainer();

 $ac = $ctn->addSingleRowCol()->addDiv();
 $ac->addABtn($ctrl->getServiceUri()."/wsdl/1?r=1")->Content = R::ngets("btn.srv.genWSDL");

 if ($ctrl->getUseDataSchema())
	$ac->addABtn(igk_getctrl("api")->getAppUri("datadb/ctrl_gen_schema/".$ctrl->Name))->Content = R::ngets("btn.srv.genXmlDataSchema");
 $ac->addABtn(igk_getctrl("api")->getAppUri("ctrl/initDb/".$ctrl->Name))->Content = R::ngets("btn.srv.InitDb");
 $ac->addABtn(igk_getctrl("api")->getAppUri("ctrl/resetDb/".$ctrl->Name))->Content = R::ngets("btn.srv.resetDb");

 $row = $ctn->addRow();

 $frm = $row->addCol()->addDiv()->addForm();
 $frm["action"]  = $ctrl->getUri("cachewsl");
 $frm["igk-ajx-form"] = 1;
 $i  = $frm->add("input")->setAttributes(array("id"=>"btnCache", "type"=>"submit",
 "value"=>"Cache WSDL"
 ));
 $i["class"] =  "igk-btn";
 if ($ctrl->Configs->clServiceDisableWSDLCache){
	  $i["class"] =  "+igk-active";
 }


 $row->addCol()->addDiv()->addABtn($ctrl->getServiceUri()."/clearwsdl_cache")->Content = R::ngets("btn.clearWSDLCache");
 $t->addDiv()->addContainer()->addSingleRowCol()->addDiv()->addIGKCopyright();