<div>
	<form method="POST" action="." class="igk-form">
		<div class="content">
			<div class="wrap">
				<h1 class="wp-heading-inline">White Books</h1>
			</div>
		</div>
	</form>
	<form method="POST" action="." class="igk-form">
		<div class="content">
			<p>
				<div class="igk-action-bar">
					<a href="#" class="button" [click]="igk.ajx.get('add',null,'');" >Add Book</a>
					<a href="?page=ilm://white_book&action=dumpdb" class="button">Dump Pages</a>
				</div>
			</p>
		</div>
	</form>
	<p>No books founds.</p>
</div>