<div>
	<form method="POST" action="." class="igk-form">
		<div class="content">
			<div class="wrap">
				<h1 class="wp-heading-inline">White Books</h1>
			</div>
		</div>
	</form>
	<form method="POST" action="." class="igk-form">
		<div class="content">
			<p>
				<div class="igk-action-bar">
					<a href="#" class="button" [click]="igk.ajx.get('add',null,'');" >Add Book</a>
					<a href="?page=ilm://white_book&action=dumpdb" class="button">Dump Pages</a>
				</div>
			</p>
		</div>
	</form>
	<form method="POST" action="." class="igk-form">
		<div class="content">
			<div class="igk-table-host">
				<table class="igk-table wp-list-table fixed striped table-view-list pages">
					<tr>

						<th><input type="checkbox" class="manage-column column-cb check-column" /></th>
						<th>picture</th>
						<th>name</th>
						<th>title</th>
						<th>desc</th>
						<th>download</th>
						<th>
								&nbsp;
						</th>
					</tr>

					<tr>
						<td>
							<input type="checkbox" name="list[]" id="list[]" />
						</td>
						<td>
							<google_icons></google_icons>
						</td>
						<td>
							<a href="#" [click]="igk.ajx.get('#',null,'');" >Kurtis Runte</a>
						</td>
						<td>Mr.</td>
						<td></td>
						<td>0</td>
						<td>
							<google_icons></google_icons>
						</td>
						<td>
							<google_icons></google_icons>
						</td>
					</tr>
					<tr>
						<td>
							<input type="checkbox" name="list[]" id="list[]" />
						</td>
						<td>
							<google_icons></google_icons>
						</td>
						<td>
							<a href="#" [click]="igk.ajx.get('#',null,'');" >Cortez Schowalter</a>
						</td>
						<td>Mr.</td>
						<td></td>
						<td>0</td>
						<td>
							<google_icons></google_icons>
						</td>
						<td>
							<google_icons></google_icons>
						</td>
					</tr>
					<tr>
						<td>
							<input type="checkbox" name="list[]" id="list[]" />
						</td>
						<td>
							<google_icons></google_icons>
						</td>
						<td>
							<a href="#" [click]="igk.ajx.get('#',null,'');" >Ms. Yolanda Rolfson PhD</a>
						</td>
						<td>Prof.</td>
						<td></td>
						<td>0</td>
						<td>
							<google_icons></google_icons>
						</td>
						<td>
							<google_icons></google_icons>
						</td>
					</tr>
					<tr>
						<td>
							<input type="checkbox" name="list[]" id="list[]" />
						</td>
						<td>
							<google_icons></google_icons>
						</td>
						<td>
							<a href="#" [click]="igk.ajx.get('#',null,'');" >Myles Fay</a>
						</td>
						<td>Prof.</td>
						<td></td>
						<td>0</td>
						<td>
							<google_icons></google_icons>
						</td>
						<td>
							<google_icons></google_icons>
						</td>
					</tr>
					<tr>
						<td>
							<input type="checkbox" name="list[]" id="list[]" />
						</td>
						<td>
							<google_icons></google_icons>
						</td>
						<td>
							<a href="#" [click]="igk.ajx.get('#',null,'');" >Dr. Breanne Pfannerstill</a>
						</td>
						<td>Miss</td>
						<td></td>
						<td>0</td>
						<td>
							<google_icons></google_icons>
						</td>
						<td>
							<google_icons></google_icons>
						</td>
					</tr>
					<tr>
						<td>
							<input type="checkbox" name="list[]" id="list[]" />
						</td>
						<td>
							<google_icons></google_icons>
						</td>
						<td>
							<a href="#" [click]="igk.ajx.get('#',null,'');" >Lelia Towne</a>
						</td>
						<td>Dr.</td>
						<td></td>
						<td>0</td>
						<td>
							<google_icons></google_icons>
						</td>
						<td>
							<google_icons></google_icons>
						</td>
					</tr>
					<tr>
						<td>
							<input type="checkbox" name="list[]" id="list[]" />
						</td>
						<td>
							<google_icons></google_icons>
						</td>
						<td>
							<a href="#" [click]="igk.ajx.get('#',null,'');" >Dr. Dagmar Crist</a>
						</td>
						<td>Mr.</td>
						<td></td>
						<td>0</td>
						<td>
							<google_icons></google_icons>
						</td>
						<td>
							<google_icons></google_icons>
						</td>
					</tr>
					<tr>
						<td>
							<input type="checkbox" name="list[]" id="list[]" />
						</td>
						<td>
							<google_icons></google_icons>
						</td>
						<td>
							<a href="#" [click]="igk.ajx.get('#',null,'');" >Kaylie Quigley</a>
						</td>
						<td>Mrs.</td>
						<td></td>
						<td>0</td>
						<td>
							<google_icons></google_icons>
						</td>
						<td>
							<google_icons></google_icons>
						</td>
					</tr>
					<tr>
						<td>
							<input type="checkbox" name="list[]" id="list[]" />
						</td>
						<td>
							<google_icons></google_icons>
						</td>
						<td>
							<a href="#" [click]="igk.ajx.get('#',null,'');" >Alize Steuber IV</a>
						</td>
						<td>Prof.</td>
						<td></td>
						<td>0</td>
						<td>
							<google_icons></google_icons>
						</td>
						<td>
							<google_icons></google_icons>
						</td>
					</tr>
					<tr>
						<td>
							<input type="checkbox" name="list[]" id="list[]" />
						</td>
						<td>
							<google_icons></google_icons>
						</td>
						<td>
							<a href="#" [click]="igk.ajx.get('#',null,'');" >Blanca Schulist</a>
						</td>
						<td>Dr.</td>
						<td></td>
						<td>0</td>
						<td>
							<google_icons></google_icons>
						</td>
						<td>
							<google_icons></google_icons>
						</td>
					</tr>
					<tr>
						<td>
							<input type="checkbox" name="list[]" id="list[]" />
						</td>
						<td>
							<google_icons></google_icons>
						</td>
						<td>
							<a href="#" [click]="igk.ajx.get('#',null,'');" >Marisol Swaniawski II</a>
						</td>
						<td>Mr.</td>
						<td></td>
						<td>0</td>
						<td>
							<google_icons></google_icons>
						</td>
						<td>
							<google_icons></google_icons>
						</td>
					</tr>
					<tr>
						<td>
							<input type="checkbox" name="list[]" id="list[]" />
						</td>
						<td>
							<google_icons></google_icons>
						</td>
						<td>
							<a href="#" [click]="igk.ajx.get('#',null,'');" >Norris Ebert</a>
						</td>
						<td>Prof.</td>
						<td></td>
						<td>0</td>
						<td>
							<google_icons></google_icons>
						</td>
						<td>
							<google_icons></google_icons>
						</td>
					</tr>
					<tr>
						<td>
							<input type="checkbox" name="list[]" id="list[]" />
						</td>
						<td>
							<google_icons></google_icons>
						</td>
						<td>
							<a href="#" [click]="igk.ajx.get('#',null,'');" >Mr. Alexys Altenwerth</a>
						</td>
						<td>Dr.</td>
						<td></td>
						<td>0</td>
						<td>
							<google_icons></google_icons>
						</td>
						<td>
							<google_icons></google_icons>
						</td>
					</tr>
					<tr>
						<td>
							<input type="checkbox" name="list[]" id="list[]" />
						</td>
						<td>
							<google_icons></google_icons>
						</td>
						<td>
							<a href="#" [click]="igk.ajx.get('#',null,'');" >Mr. Vaughn Kuhn Jr.</a>
						</td>
						<td>Mr.</td>
						<td></td>
						<td>0</td>
						<td>
							<google_icons></google_icons>
						</td>
						<td>
							<google_icons></google_icons>
						</td>
					</tr>
					<tr>
						<td>
							<input type="checkbox" name="list[]" id="list[]" />
						</td>
						<td>
							<google_icons></google_icons>
						</td>
						<td>
							<a href="#" [click]="igk.ajx.get('#',null,'');" >Charlene Quigley</a>
						</td>
						<td>Dr.</td>
						<td></td>
						<td>0</td>
						<td>
							<google_icons></google_icons>
						</td>
						<td>
							<google_icons></google_icons>
						</td>
					</tr>
					<tr>
						<td>
							<input type="checkbox" name="list[]" id="list[]" />
						</td>
						<td>
							<google_icons></google_icons>
						</td>
						<td>
							<a href="#" [click]="igk.ajx.get('#',null,'');" >Melany Brown V</a>
						</td>
						<td>Mr.</td>
						<td></td>
						<td>0</td>
						<td>
							<google_icons></google_icons>
						</td>
						<td>
							<google_icons></google_icons>
						</td>
					</tr>
					<tr>
						<td>
							<input type="checkbox" name="list[]" id="list[]" />
						</td>
						<td>
							<google_icons></google_icons>
						</td>
						<td>
							<a href="#" [click]="igk.ajx.get('#',null,'');" >Miss Tania Skiles</a>
						</td>
						<td>Ms.</td>
						<td></td>
						<td>0</td>
						<td>
							<google_icons></google_icons>
						</td>
						<td>
							<google_icons></google_icons>
						</td>
					</tr>
					<tr>
						<td>
							<input type="checkbox" name="list[]" id="list[]" />
						</td>
						<td>
							<google_icons></google_icons>
						</td>
						<td>
							<a href="#" [click]="igk.ajx.get('#',null,'');" >Cameron Wisoky</a>
						</td>
						<td>Dr.</td>
						<td></td>
						<td>0</td>
						<td>
							<google_icons></google_icons>
						</td>
						<td>
							<google_icons></google_icons>
						</td>
					</tr>
					<tr>
						<td>
							<input type="checkbox" name="list[]" id="list[]" />
						</td>
						<td>
							<google_icons></google_icons>
						</td>
						<td>
							<a href="#" [click]="igk.ajx.get('#',null,'');" >Ruth Durgan</a>
						</td>
						<td>Prof.</td>
						<td></td>
						<td>0</td>
						<td>
							<google_icons></google_icons>
						</td>
						<td>
							<google_icons></google_icons>
						</td>
					</tr>
					<tr>
						<td>
							<input type="checkbox" name="list[]" id="list[]" />
						</td>
						<td>
							<google_icons></google_icons>
						</td>
						<td>
							<a href="#" [click]="igk.ajx.get('#',null,'');" >Claude Lueilwitz II</a>
						</td>
						<td>Prof.</td>
						<td></td>
						<td>0</td>
						<td>
							<google_icons></google_icons>
						</td>
						<td>
							<google_icons></google_icons>
						</td>
					</tr>
				</table>
			</div>
		</div>
	</form>
</div>