<?php
// file: books.phtml
// author: C.A.D. BONDJE DOUE
// desc: download view
use function ilm_resources_gets as __;

?><div>
    <ul>
        <?php
        foreach ($books as $book) {
            echo "<li>" . $book->book_name . "</li>";
            echo "<li>" . $book->book_title . "</li>";
            echo "<li><a href='./wbook/download/{$book->book_id}' class='button'>" . __("Download") . "</a></li>";
        }
        ?>
    </ul>
</div>